[2023-09-01T13:07:54.197+0900] {processor.py:157} INFO - Started process (PID=2177) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:07:54.198+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:07:54.200+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:07:54.199+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:07:54.205+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:07:54.204+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:07:54.206+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:07:54.205+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:07:54.206+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:07:54.217+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-09-01T13:08:44.792+0900] {processor.py:157} INFO - Started process (PID=3760) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:08:44.794+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:08:44.796+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:08:44.795+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:08:44.801+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:08:44.800+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:08:44.801+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:08:44.801+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:08:44.801+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:08:44.814+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-09-01T13:09:36.248+0900] {processor.py:157} INFO - Started process (PID=4389) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:09:36.250+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:09:36.251+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:09:36.250+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:09:36.257+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:09:36.256+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:09:36.257+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:09:36.257+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:09:36.257+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:09:36.269+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-09-01T13:10:23.719+0900] {processor.py:157} INFO - Started process (PID=4851) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:10:23.720+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:10:23.722+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:10:23.721+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:10:23.727+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:10:23.726+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:10:23.728+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:10:23.727+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:10:23.728+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:10:23.739+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-09-01T13:11:10.734+0900] {processor.py:157} INFO - Started process (PID=5293) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:11:10.735+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:11:10.737+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:11:10.736+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:11:10.741+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:11:10.740+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:11:10.741+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:11:10.741+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:11:10.741+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:11:10.751+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-09-01T13:13:09.036+0900] {processor.py:157} INFO - Started process (PID=6005) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:13:09.038+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:13:09.039+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:13:09.039+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:13:09.042+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:13:09.041+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:13:09.042+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:13:09.042+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:13:09.042+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:13:09.050+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2023-09-01T13:13:53.553+0900] {processor.py:157} INFO - Started process (PID=6461) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:13:53.554+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:13:53.556+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:13:53.555+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:13:53.561+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:13:53.560+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:13:53.561+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:13:53.561+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:13:53.561+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:13:53.572+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-09-01T13:14:36.530+0900] {processor.py:157} INFO - Started process (PID=7363) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:14:36.531+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:14:36.532+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:14:36.531+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:14:36.535+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:14:36.534+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:14:36.535+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:14:36.535+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:14:36.535+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:14:36.542+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2023-09-01T13:15:20.917+0900] {processor.py:157} INFO - Started process (PID=7881) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:15:20.918+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:15:20.920+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:15:20.919+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:15:20.926+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:15:20.925+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:15:20.926+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:15:20.926+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:15:20.927+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:15:20.939+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-09-01T13:16:08.938+0900] {processor.py:157} INFO - Started process (PID=8381) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:16:08.940+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:16:08.941+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:16:08.940+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:16:08.947+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:16:08.946+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:16:08.947+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:16:08.947+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:16:08.947+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:16:08.959+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-09-01T13:16:52.427+0900] {processor.py:157} INFO - Started process (PID=8800) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:16:52.428+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:16:52.430+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:16:52.429+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:16:52.434+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:16:52.434+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:16:52.435+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:16:52.434+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:16:52.435+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:16:52.446+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-09-01T13:17:40.135+0900] {processor.py:157} INFO - Started process (PID=9266) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:17:40.137+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:17:40.138+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:17:40.137+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:17:40.142+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:17:40.142+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:17:40.143+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:17:40.142+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:17:40.143+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:17:40.153+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-09-01T13:18:26.788+0900] {processor.py:157} INFO - Started process (PID=9766) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:18:26.790+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:18:26.792+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:18:26.791+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:18:26.797+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:18:26.796+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:18:26.797+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:18:26.797+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:18:26.798+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:18:26.809+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-09-01T13:19:11.133+0900] {processor.py:157} INFO - Started process (PID=10194) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:19:11.134+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:19:11.136+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:19:11.135+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:19:11.140+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:19:11.140+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:19:11.140+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:19:11.140+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:19:11.141+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:19:11.152+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-09-01T13:19:55.753+0900] {processor.py:157} INFO - Started process (PID=10621) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:19:55.754+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:19:55.756+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:19:55.755+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:19:55.760+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:19:55.760+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:19:55.761+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:19:55.761+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:19:55.761+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:19:55.772+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-09-01T13:20:39.183+0900] {processor.py:157} INFO - Started process (PID=11071) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:20:39.185+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:20:39.186+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:20:39.185+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:20:39.192+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:20:39.191+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:20:39.193+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:20:39.192+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:20:39.193+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:20:39.205+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-09-01T13:21:44.195+0900] {processor.py:157} INFO - Started process (PID=11622) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:21:44.196+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:21:44.197+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:21:44.197+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:21:44.200+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:21:44.199+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:21:44.200+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:21:44.200+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:21:44.200+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:21:44.206+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2023-09-01T13:22:28.153+0900] {processor.py:157} INFO - Started process (PID=12042) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:22:28.155+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:22:28.156+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:22:28.155+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:22:28.161+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:22:28.160+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:22:28.161+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:22:28.161+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:22:28.162+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:22:28.172+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-09-01T13:23:11.813+0900] {processor.py:157} INFO - Started process (PID=12462) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:23:11.814+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:23:11.815+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:23:11.814+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:23:11.818+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:23:11.818+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:23:11.819+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:23:11.819+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:23:11.819+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:23:11.829+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-09-01T13:23:54.697+0900] {processor.py:157} INFO - Started process (PID=12911) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:23:54.699+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:23:54.701+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:23:54.700+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:23:54.705+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:23:54.705+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:23:54.706+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:23:54.706+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:23:54.706+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:23:54.716+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-09-01T13:24:43.104+0900] {processor.py:157} INFO - Started process (PID=13403) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:24:43.105+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:24:43.107+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:24:43.106+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:24:43.111+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:24:43.110+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:24:43.111+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:24:43.111+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:24:43.111+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:24:43.120+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-09-01T13:26:17.163+0900] {processor.py:157} INFO - Started process (PID=14598) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:26:17.166+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:26:17.168+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:26:17.166+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:26:17.173+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:26:17.172+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:26:17.173+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:26:17.173+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:26:17.173+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:26:17.184+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-09-01T13:27:02.224+0900] {processor.py:157} INFO - Started process (PID=15039) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:27:02.226+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:27:02.227+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:27:02.226+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:27:02.232+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:27:02.231+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:27:02.232+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:27:02.232+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:27:02.232+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:27:02.243+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-09-01T13:27:47.397+0900] {processor.py:157} INFO - Started process (PID=15465) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:27:47.399+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:27:47.400+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:27:47.399+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:27:47.404+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:27:47.404+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:27:47.405+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:27:47.405+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:27:47.405+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:27:47.416+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-09-01T13:28:31.828+0900] {processor.py:157} INFO - Started process (PID=15899) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:28:31.830+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:28:31.831+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:28:31.830+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:28:31.836+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:28:31.835+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:28:31.836+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:28:31.836+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:28:31.836+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:28:31.848+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-09-01T13:29:20.177+0900] {processor.py:157} INFO - Started process (PID=16396) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:29:20.178+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:29:20.179+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:29:20.179+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:29:20.184+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:29:20.183+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:29:20.184+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:29:20.184+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:29:20.184+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:29:20.195+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-09-01T13:30:08.776+0900] {processor.py:157} INFO - Started process (PID=16867) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:30:08.777+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:30:08.778+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:30:08.777+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:30:08.781+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:30:08.780+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:30:08.781+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:30:08.781+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:30:08.781+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:30:08.788+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2023-09-01T13:30:52.193+0900] {processor.py:157} INFO - Started process (PID=17279) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:30:52.194+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:30:52.195+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:30:52.195+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:30:52.198+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:30:52.198+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:30:52.198+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:30:52.198+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:30:52.198+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:30:52.205+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2023-09-01T13:31:34.362+0900] {processor.py:157} INFO - Started process (PID=17691) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:31:34.364+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:31:34.366+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:31:34.365+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:31:34.371+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:31:34.370+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:31:34.371+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:31:34.371+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:31:34.371+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:31:34.382+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-09-01T13:32:20.116+0900] {processor.py:157} INFO - Started process (PID=18139) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:32:20.118+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:32:20.119+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:32:20.119+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:32:20.124+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:32:20.123+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:32:20.124+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:32:20.124+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:32:20.124+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:32:20.135+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-09-01T13:33:03.611+0900] {processor.py:157} INFO - Started process (PID=18557) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:33:03.612+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:33:03.613+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:33:03.613+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:33:03.618+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:33:03.617+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:33:03.618+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:33:03.618+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:33:03.619+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:33:03.630+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-09-01T13:33:53.772+0900] {processor.py:157} INFO - Started process (PID=19058) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:33:53.773+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:33:53.774+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:33:53.773+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:33:53.778+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:33:53.777+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:33:53.778+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:33:53.778+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:33:53.779+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:33:53.790+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-09-01T13:34:38.154+0900] {processor.py:157} INFO - Started process (PID=19494) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:34:38.157+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:34:38.158+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:34:38.157+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:34:38.162+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:34:38.162+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:34:38.163+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:34:38.163+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:34:38.163+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:34:38.174+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-09-01T13:35:21.075+0900] {processor.py:157} INFO - Started process (PID=19918) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:35:21.077+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:35:21.079+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:35:21.078+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:35:21.084+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:35:21.083+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:35:21.084+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:35:21.084+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:35:21.084+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:35:21.095+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-09-01T13:36:05.587+0900] {processor.py:157} INFO - Started process (PID=20338) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:36:05.589+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:36:05.590+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:36:05.589+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:36:05.595+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:36:05.594+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:36:05.595+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:36:05.595+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:36:05.595+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:36:05.605+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-09-01T13:36:54.616+0900] {processor.py:157} INFO - Started process (PID=20811) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:36:54.618+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:36:54.620+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:36:54.619+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:36:54.624+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:36:54.623+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:36:54.624+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:36:54.624+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:36:54.625+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:36:54.636+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-09-01T13:37:39.577+0900] {processor.py:157} INFO - Started process (PID=21248) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:37:39.578+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:37:39.579+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:37:39.578+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:37:39.582+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:37:39.582+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:37:39.582+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:37:39.582+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:37:39.582+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:37:39.590+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2023-09-01T13:38:24.787+0900] {processor.py:157} INFO - Started process (PID=21690) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:38:24.789+0900] {processor.py:829} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-01T13:38:24.790+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:38:24.789+0900] {dagbag.py:539} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:38:24.795+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:38:24.794+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-01T13:38:24.795+0900] {logging_mixin.py:151} INFO - [2023-09-01T13:38:24.795+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-01T13:38:24.795+0900] {processor.py:841} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-01T13:38:24.807+0900] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
